--------------------------------------------------------
--  Fichier créé - mardi-décembre-17-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FEATURE
--------------------------------------------------------

  CREATE TABLE "RJAB"."FEATURE" 
   (	"REFERENCE" NUMBER, 
	"DATE_FACTURATION" DATE, 
	"DATE_PAIEMENT" DATE, 
	"REMISE" NUMBER, 
	"ID" NUMBER, 
	"SERVICE_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "RJAB"."CLIENT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"CONTACT" NUMBER, 
	"IDENTIFIANT" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "RJAB"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTENAIRE
--------------------------------------------------------

  CREATE TABLE "RJAB"."PARTENAIRE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"CONTACT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "RJAB"."PRODUIT" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "RJAB"."REVIEW" 
   (	"ID" NUMBER, 
	"SCORE" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "RJAB"."SERVICES" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ID" NUMBER, 
	"FEATURE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into RJAB.FEATURE
SET DEFINE OFF;
REM INSERTING into RJAB.CLIENT
SET DEFINE OFF;
Insert into RJAB.CLIENT (NOM,CONTACT,IDENTIFIANT,ADRESSE) values ('Rjab','123456','23','ariana');
Insert into RJAB.CLIENT (NOM,CONTACT,IDENTIFIANT,ADRESSE) values ('aminee','111','25','maktherr ');
Insert into RJAB.CLIENT (NOM,CONTACT,IDENTIFIANT,ADRESSE) values ('amine','987282','19','makthar');
Insert into RJAB.CLIENT (NOM,CONTACT,IDENTIFIANT,ADRESSE) values ('HNAK','22','17','ariana');
REM INSERTING into RJAB.EMPLOYE
SET DEFINE OFF;
REM INSERTING into RJAB.PARTENAIRE
SET DEFINE OFF;
REM INSERTING into RJAB.PRODUIT
SET DEFINE OFF;
REM INSERTING into RJAB.REVIEW
SET DEFINE OFF;
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('1','3','good app');
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('2','4','aze');
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('3','4','yatik sahha');
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('4','5','lkhidma behya');
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('5','5','behya lkhidma');
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('21','2','BARAKA AALAHOU FIK');
Insert into RJAB.REVIEW (ID,SCORE,DESCRIPTION) values ('41','5','BUYYU');
REM INSERTING into RJAB.SERVICES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FEATURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."FEATURE_PK" ON "RJAB"."FEATURE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."CLIENT_PK" ON "RJAB"."CLIENT" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."EMPLOYE_PK" ON "RJAB"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTENAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."PARTENAIRE_PK" ON "RJAB"."PARTENAIRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."PRODUIT_PK" ON "RJAB"."PRODUIT" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007025
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."SYS_C007025" ON "RJAB"."REVIEW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RJAB"."SERVICES_PK" ON "RJAB"."SERVICES" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CLIENT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RJAB"."CLIENT_ID_TRIGGER" 
BEFORE INSERT ON CLIENT
FOR EACH ROW
BEGIN
   -- Ensure the sequence is used
   :NEW.IDENTIFIANT := client_seq.NEXTVAL;
END;
/
ALTER TRIGGER "RJAB"."CLIENT_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEW_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RJAB"."REVIEW_BIR" 
BEFORE INSERT ON review 
FOR EACH ROW
BEGIN
  SELECT review_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;

/
ALTER TRIGGER "RJAB"."REVIEW_BIR" ENABLE;
--------------------------------------------------------
--  Constraints for Table FEATURE
--------------------------------------------------------

  ALTER TABLE "RJAB"."FEATURE" ADD CONSTRAINT "FEATURE_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."FEATURE" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "RJAB"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."CLIENT" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "RJAB"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTENAIRE
--------------------------------------------------------

  ALTER TABLE "RJAB"."PARTENAIRE" ADD CONSTRAINT "PARTENAIRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."PARTENAIRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "RJAB"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."PRODUIT" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "RJAB"."REVIEW" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."REVIEW" ADD CHECK (score BETWEEN 1 AND 5) ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "RJAB"."SERVICES" ADD CONSTRAINT "SERVICES_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RJAB"."SERVICES" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FEATURE
--------------------------------------------------------

  ALTER TABLE "RJAB"."FEATURE" ADD CONSTRAINT "FEATURE_FK1" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "RJAB"."SERVICES" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "RJAB"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_FK1" FOREIGN KEY ("NOM")
	  REFERENCES "RJAB"."SERVICES" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTENAIRE
--------------------------------------------------------

  ALTER TABLE "RJAB"."PARTENAIRE" ADD CONSTRAINT "PARTENAIRE_FK1" FOREIGN KEY ("NOM")
	  REFERENCES "RJAB"."PRODUIT" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "RJAB"."PRODUIT" ADD CONSTRAINT "PRODUIT_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "RJAB"."SERVICES" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "RJAB"."SERVICES" ADD CONSTRAINT "SERVICES_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "RJAB"."CLIENT" ("IDENTIFIANT") ENABLE;
  ALTER TABLE "RJAB"."SERVICES" ADD CONSTRAINT "SERVICES_FK2" FOREIGN KEY ("MATRICULE")
	  REFERENCES "RJAB"."PRODUIT" ("MATRICULE") ENABLE;
  ALTER TABLE "RJAB"."SERVICES" ADD CONSTRAINT "SERVICES_FK3" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "RJAB"."EMPLOYE" ("ID") ENABLE;
  ALTER TABLE "RJAB"."SERVICES" ADD CONSTRAINT "SERVICES_FK4" FOREIGN KEY ("FEATURE_ID")
	  REFERENCES "RJAB"."FEATURE" ("REFERENCE") ENABLE;
